metadata:
  device_name: "Tokamak T-10"
#--------------------------
# PHYSICS PARAMS
#--------------------------
physical_params:
  B : 2.84 #T
  E_ION : 13.598 #eV
  T_MIN : 20.0 #eV
  N_MIN : 3.0e12 #cm^{-3}
  T_MAX : 1315.454 #eV
  N_MAX : 3.33e13 #cm^{-3}
  A_MIN : 32.0 #cm
  LAMBDA_N : 1.0e-3
  LAMBDA_T : 1.0e-3
  P_EXT : 2.5e18 # eV/cm^3 s
  VAR : 1.12
  MU : 0.375
  N_0 : 1.0e2
  l : 17.5
#---------------------------
# NETWORK PARAMETERS
#---------------------------
hidden_layers : 32
#---------------------------
# MODEL PARAMETERS
#---------------------------
model_params:
  NUM_DOMAIN : 1000
  NUM_BOUNDARY : 1
  NUM_TEST : 200
  LOSS_WEIGHTS : [0.1, 0.001, 1.0, 1.0, 0.1, 0.1]
  ADAM_ITER1 : 2000
  ADAM_ITER2 : 5000
#---------------------------
# PREDICTION PARAMETERS
#---------------------------
num_observations : 41

